-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.app_lifecycle_logs
(
    log_id bigserial NOT NULL,
    session_id text COLLATE pg_catalog."default" NOT NULL,
    event_type text COLLATE pg_catalog."default" NOT NULL,
    event_source text COLLATE pg_catalog."default" NOT NULL DEFAULT 'APP'::text,
    notes text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT app_lifecycle_logs_pkey PRIMARY KEY (log_id)
);

CREATE TABLE IF NOT EXISTS public.bill_audit
(
    audit_id bigserial NOT NULL,
    bill_id text COLLATE pg_catalog."default" NOT NULL,
    action_type text COLLATE pg_catalog."default" NOT NULL,
    action_source text COLLATE pg_catalog."default" NOT NULL DEFAULT 'BILLING_UI'::text,
    action_at timestamp with time zone NOT NULL DEFAULT now(),
    previous_payment_mode text COLLATE pg_catalog."default" NOT NULL,
    previous_discount_mode text COLLATE pg_catalog."default" NOT NULL,
    previous_discount_value double precision NOT NULL,
    previous_item_count integer NOT NULL,
    previous_subtotal_paise integer NOT NULL,
    previous_discount_paise integer NOT NULL,
    previous_grand_total_paise integer NOT NULL,
    previous_items_json jsonb NOT NULL,
    new_payment_mode text COLLATE pg_catalog."default",
    new_discount_mode text COLLATE pg_catalog."default",
    new_discount_value double precision,
    new_item_count integer,
    new_subtotal_paise integer,
    new_discount_paise integer,
    new_grand_total_paise integer,
    new_items_json jsonb,
    CONSTRAINT bill_audit_pkey PRIMARY KEY (audit_id)
);

CREATE TABLE IF NOT EXISTS public.bills
(
    bill_id text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    payment_mode text COLLATE pg_catalog."default" NOT NULL DEFAULT 'CASH'::text,
    discount_mode text COLLATE pg_catalog."default" NOT NULL DEFAULT 'PERCENT'::text,
    discount_value double precision NOT NULL DEFAULT 0,
    item_count integer NOT NULL DEFAULT 0,
    subtotal_paise integer NOT NULL DEFAULT 0,
    discount_paise integer NOT NULL DEFAULT 0,
    grand_total_paise integer NOT NULL DEFAULT 0,
    items_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    CONSTRAINT bills_pkey PRIMARY KEY (bill_id)
);

CREATE TABLE IF NOT EXISTS public.bulk_import_batch
(
    batch_id text COLLATE pg_catalog."default" NOT NULL,
    operation_type text COLLATE pg_catalog."default" NOT NULL,
    file_name text COLLATE pg_catalog."default",
    started_at timestamp with time zone,
    applied_at timestamp with time zone NOT NULL DEFAULT now(),
    row_count integer NOT NULL DEFAULT 0,
    processed_count integer NOT NULL DEFAULT 0,
    inserted_count integer NOT NULL DEFAULT 0,
    updated_count integer NOT NULL DEFAULT 0,
    success_count integer NOT NULL DEFAULT 0,
    failed_count integer NOT NULL DEFAULT 0,
    skipped_count integer NOT NULL DEFAULT 0,
    items_json text COLLATE pg_catalog."default" NOT NULL DEFAULT '[]'::text,
    reverted_at timestamp with time zone,
    reverted integer NOT NULL DEFAULT 0,
    CONSTRAINT bulk_import_batch_pkey PRIMARY KEY (batch_id)
);

CREATE TABLE IF NOT EXISTS public.held_bills
(
    hold_id text COLLATE pg_catalog."default" NOT NULL,
    bill_data_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    held_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT held_bills_pkey PRIMARY KEY (hold_id)
);

CREATE TABLE IF NOT EXISTS public.inventory_audit
(
    audit_id bigserial NOT NULL,
    product_id text COLLATE pg_catalog."default" NOT NULL,
    action_type text COLLATE pg_catalog."default" NOT NULL,
    qty_delta numeric(12, 3) NOT NULL DEFAULT 0.000,
    weight_delta numeric(12, 3) NOT NULL DEFAULT 0.000,
    prev_qty numeric(12, 3) NOT NULL DEFAULT 0.000,
    new_qty numeric(12, 3) NOT NULL DEFAULT 0.000,
    prev_weight numeric(12, 3) NOT NULL DEFAULT 0.000,
    new_weight numeric(12, 3) NOT NULL DEFAULT 0.000,
    bill_id text COLLATE pg_catalog."default",
    reference_id text COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT inventory_audit_pkey PRIMARY KEY (audit_id)
);

CREATE TABLE IF NOT EXISTS public.product_audit
(
    audit_id bigserial NOT NULL,
    item_id text COLLATE pg_catalog."default" NOT NULL,
    action_type text COLLATE pg_catalog."default" NOT NULL,
    previous_name text COLLATE pg_catalog."default",
    previous_category text COLLATE pg_catalog."default",
    previous_sku text COLLATE pg_catalog."default",
    previous_pricing_type text COLLATE pg_catalog."default",
    previous_rate integer,
    new_name text COLLATE pg_catalog."default",
    new_category text COLLATE pg_catalog."default",
    new_sku text COLLATE pg_catalog."default",
    new_pricing_type text COLLATE pg_catalog."default",
    new_rate integer,
    action_source text COLLATE pg_catalog."default" NOT NULL DEFAULT 'ITEMS_UI'::text,
    action_at timestamp with time zone NOT NULL DEFAULT now(),
    previous_brand_name text COLLATE pg_catalog."default",
    previous_retail_price_paise integer,
    previous_wholesale_price_paise integer,
    previous_wholesale_min_qty numeric(12, 3),
    new_brand_name text COLLATE pg_catalog."default",
    new_retail_price_paise integer,
    new_wholesale_price_paise integer,
    new_wholesale_min_qty numeric(12, 3),
    CONSTRAINT product_audit_pkey PRIMARY KEY (audit_id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    category text COLLATE pg_catalog."default" NOT NULL DEFAULT 'UNCATEGORIZED'::text,
    sku text COLLATE pg_catalog."default" NOT NULL,
    pricing_type text COLLATE pg_catalog."default" NOT NULL,
    rate integer NOT NULL,
    inv_track_type text COLLATE pg_catalog."default" DEFAULT 'none'::text,
    inv_current_qty numeric(12, 3) DEFAULT 0.000,
    inv_current_weight numeric(12, 3) DEFAULT 0.000,
    inv_unit text COLLATE pg_catalog."default" DEFAULT 'piece'::text,
    inv_min_qty numeric(12, 3) DEFAULT 0.000,
    inv_min_weight numeric(12, 3) DEFAULT 0.000,
    name_ta text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    brand_name text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    retail_price_paise integer NOT NULL DEFAULT 0,
    wholesale_price_paise integer,
    wholesale_min_qty numeric(12, 3),
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT products_sku_key UNIQUE (sku)
);

CREATE TABLE IF NOT EXISTS public.settings
(
    id text COLLATE pg_catalog."default" NOT NULL,
    type text COLLATE pg_catalog."default" NOT NULL,
    value text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT settings_pkey PRIMARY KEY (id)
);
END;

-- -----------------------------------------------------------------------------
-- Application database user (read/write on app tables only, no audit tables)
-- Replace the password before using in non-local environments.
-- -----------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pos_app_user') THEN
        CREATE ROLE pos_app_user LOGIN PASSWORD 'change_me_strong_password';
    END IF;
END
$$;

ALTER ROLE pos_app_user LOGIN PASSWORD 'change_me_strong_password';

DO $$
DECLARE
    db_name text := current_database();
BEGIN
    EXECUTE format('GRANT CONNECT ON DATABASE %I TO pos_app_user', db_name);
END
$$;

GRANT USAGE ON SCHEMA public TO pos_app_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
    public.products,
    public.bills,
    public.held_bills,
    public.bulk_import_batch,
    public.settings,
    public.app_lifecycle_logs
TO pos_app_user;

GRANT USAGE, SELECT ON SEQUENCE public.app_lifecycle_logs_log_id_seq TO pos_app_user;

-- -----------------------------------------------------------------------------
-- Analytics read-only user (read on analytics/reporting tables)
-- Replace the password before using in non-local environments.
-- -----------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pos_analytics_user') THEN
        CREATE ROLE pos_analytics_user LOGIN PASSWORD 'change_me_analytics_password';
    END IF;
END
$$;

ALTER ROLE pos_analytics_user LOGIN PASSWORD 'change_me_analytics_password';

DO $$
DECLARE
    db_name text := current_database();
BEGIN
    EXECUTE format('GRANT CONNECT ON DATABASE %I TO pos_analytics_user', db_name);
END
$$;

GRANT USAGE ON SCHEMA public TO pos_analytics_user;

GRANT SELECT ON TABLE
    public.products,
    public.bills,
    public.held_bills,
    public.bulk_import_batch,
    public.app_lifecycle_logs,
    public.bill_audit,
    public.inventory_audit,
    public.product_audit
TO pos_analytics_user;

-- -----------------------------------------------------------------------------
-- Admin user (read/write on all tables)
-- Replace the password before using in non-local environments.
-- -----------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pos_admin_user') THEN
        CREATE ROLE pos_admin_user LOGIN PASSWORD 'change_me_admin_password';
    END IF;
END
$$;

ALTER ROLE pos_admin_user LOGIN PASSWORD 'change_me_admin_password';

DO $$
DECLARE
    db_name text := current_database();
BEGIN
    EXECUTE format('GRANT CONNECT ON DATABASE %I TO pos_admin_user', db_name);
END
$$;

GRANT USAGE ON SCHEMA public TO pos_admin_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO pos_admin_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO pos_admin_user;
